export interface Product {
  id: number
  name: string
  price: number
  originalPrice?: number
  color: string
  colors: string[]
  sizes: string[]
  category: string
  image: string
  secondaryImage?: string
  href: string
  isNew?: boolean
  isBestseller?: boolean
}

export const menProducts: Product[] = [
  {
    id: 1,
    name: "Performance Training Tee",
    price: 68,
    color: "Stone",
    colors: ["Stone", "Black", "Navy", "Charcoal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1780&auto=format&fit=crop",
    secondaryImage: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=2015&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 2,
    name: "Tapered Jogger",
    price: 98,
    color: "Charcoal",
    colors: ["Charcoal", "Black", "Navy", "Olive"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=1974&auto=format&fit=crop",
    href: "#",
    isBestseller: true,
  },
  {
    id: 3,
    name: "Compression Tank",
    price: 58,
    color: "Onyx",
    colors: ["Onyx", "White", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=2070&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 4,
    name: "Training Short 7\"",
    price: 78,
    color: "Slate",
    colors: ["Slate", "Black", "Navy", "Olive"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1519058082700-08a0b56da9b4?q=80&w=2070&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 5,
    name: "Tech Hoodie",
    price: 128,
    color: "Heather Grey",
    colors: ["Heather Grey", "Black", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1974&auto=format&fit=crop",
    href: "#",
    isBestseller: true,
  },
  {
    id: 6,
    name: "Performance Polo",
    price: 88,
    color: "Navy",
    colors: ["Navy", "White", "Black", "Stone"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=2015&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 7,
    name: "Lightweight Track Pant",
    price: 108,
    color: "Black",
    colors: ["Black", "Navy", "Charcoal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1974&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 8,
    name: "Windbreaker Jacket",
    price: 148,
    color: "Olive",
    colors: ["Olive", "Black", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1936&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 9,
    name: "Long Sleeve Training Tee",
    price: 78,
    color: "White",
    colors: ["White", "Black", "Grey", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1964&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 10,
    name: "Training Short 5\"",
    price: 68,
    color: "Navy",
    colors: ["Navy", "Black", "Grey", "Olive"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?q=80&w=1854&auto=format&fit=crop",
    href: "#",
    isBestseller: true,
  },
  {
    id: 11,
    name: "Puffer Vest",
    price: 138,
    color: "Black",
    colors: ["Black", "Navy", "Olive"],
    sizes: ["S", "M", "L", "XL"],
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1544923246-77307dd628b0?q=80&w=1974&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 12,
    name: "Everyday Henley",
    price: 72,
    color: "Oatmeal",
    colors: ["Oatmeal", "Black", "Navy", "Olive"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1976&auto=format&fit=crop",
    href: "#",
  },
]

export const womenProducts: Product[] = [
  {
    id: 101,
    name: "Performance Legging",
    price: 98,
    color: "Black",
    colors: ["Black", "Navy", "Burgundy", "Forest"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=1974&auto=format&fit=crop",
    href: "#",
    isBestseller: true,
  },
  {
    id: 102,
    name: "Seamless Sports Bra",
    price: 58,
    color: "Blush",
    colors: ["Blush", "Black", "White", "Grey"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?q=80&w=1972&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 103,
    name: "Cropped Tank",
    price: 48,
    color: "White",
    colors: ["White", "Black", "Sage", "Blush"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1920&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 104,
    name: "High-Rise Bike Short",
    price: 68,
    color: "Navy",
    colors: ["Navy", "Black", "Olive", "Burgundy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=2070&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 105,
    name: "Lightweight Hoodie",
    price: 118,
    color: "Oatmeal",
    colors: ["Oatmeal", "Black", "Grey", "Sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1517298257259-f72ccd2db392?q=80&w=1974&auto=format&fit=crop",
    href: "#",
    isBestseller: true,
  },
  {
    id: 106,
    name: "Flare Legging",
    price: 108,
    color: "Black",
    colors: ["Black", "Navy", "Charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?q=80&w=1974&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 107,
    name: "Racerback Tank",
    price: 52,
    color: "Sage",
    colors: ["Sage", "Black", "White", "Blush"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1434682881908-b43d0467b798?q=80&w=1974&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 108,
    name: "Running Jacket",
    price: 138,
    color: "Black",
    colors: ["Black", "Navy", "Blush"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1483721310020-03333e577078?q=80&w=1976&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 109,
    name: "Wide-Leg Pant",
    price: 98,
    color: "Charcoal",
    colors: ["Charcoal", "Black", "Navy", "Olive"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1976&auto=format&fit=crop",
    href: "#",
    isBestseller: true,
  },
  {
    id: 110,
    name: "Long Sleeve Crop Top",
    price: 62,
    color: "White",
    colors: ["White", "Black", "Grey", "Burgundy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Tops",
    image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?q=80&w=1780&auto=format&fit=crop",
    href: "#",
  },
  {
    id: 111,
    name: "Fleece Quarter-Zip",
    price: 98,
    color: "Cream",
    colors: ["Cream", "Black", "Sage", "Grey"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?q=80&w=1962&auto=format&fit=crop",
    href: "#",
    isNew: true,
  },
  {
    id: 112,
    name: "Tennis Skirt",
    price: 78,
    color: "White",
    colors: ["White", "Black", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    category: "Bottoms",
    image: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=1974&auto=format&fit=crop",
    href: "#",
  },
]

export const categories = {
  men: ["All", "Tops", "Bottoms", "Outerwear"],
  women: ["All", "Tops", "Bottoms", "Outerwear"],
}

export const colors = [
  "Black",
  "White",
  "Navy",
  "Grey",
  "Charcoal",
  "Olive",
  "Stone",
  "Oatmeal",
  "Blush",
  "Sage",
  "Burgundy",
]

export const sizes = {
  men: ["S", "M", "L", "XL", "XXL"],
  women: ["XS", "S", "M", "L", "XL"],
}

export type SortOption = "newest" | "price-low" | "price-high" | "bestsellers"

export const sortOptions: { value: SortOption; label: string }[] = [
  { value: "newest", label: "Newest" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "bestsellers", label: "Bestsellers" },
]
